version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    volumes:
      - '.:/app'
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevConfig
      - DATABASE_URI=postgres://postgres:postgres@db:5432/svg_monitoring_dev
      - TEST_DATABASE_URI=postgres://postgres:postgres@db:5432/svg_monitoring_test
      - SECRET_KEY=supersecretdevonlykey
    depends_on:
      - db

  db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    ports:
      - 5106:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
