version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    volumes:
      - '.:/app'
    external_links:
      - svg_gateway_app_1:svg_gateway 
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevConfig
      - DATABASE_URI=postgres://postgres:postgres@db:5432/svg_monitoring_dev
      - TEST_DATABASE_URI=postgres://postgres:postgres@db:5432/svg_monitoring_test
      - SECRET_KEY=supersecretdevonlykey
      - SVG_GATEWAY_BASE_URI=http://svg_gateway:5000
    depends_on:
      - db
    networks:
      - svg_shared
      - default
  db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    ports:
      - 5107:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - default
networks:
  svg_shared:
    external:
      name: svg_shared
