"""empty message

Revision ID: 3cb4dbd6d4ab
Revises: f6bbca61e933
Create Date: 2019-11-28 20:40:25.147049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb4dbd6d4ab'
down_revision = 'f6bbca61e933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plantings', 'hours_backlit',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plantings', 'hours_backlit',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
