"""empty message

Revision ID: 41f89478a23b
Revises: 6c7f31b79821
Create Date: 2019-10-17 05:06:57.402864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f89478a23b'
down_revision = '6c7f31b79821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plantings', sa.Column('cycle_ending_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plantings', 'cycle_ending_date')
    # ### end Alembic commands ###
