"""empty message

Revision ID: 6c7f31b79821
Revises: 
Create Date: 2019-10-01 23:09:43.447883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7f31b79821'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pincode', sa.Integer(), nullable=True),
    sa.Column('raspberry_ip', sa.String(length=30), nullable=True),
    sa.Column('currently_backlit', sa.Boolean(), nullable=True),
    sa.Column('currently_irrigating', sa.Boolean(), nullable=True),
    sa.Column('smart_irrigation_enabled', sa.Boolean(), nullable=True),
    sa.Column('smart_illumination_enabled', sa.Boolean(), nullable=True),
    sa.Column('planting_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seedlings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('average_harvest_time', sa.Integer(), nullable=False),
    sa.Column('humidity_threshold', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('illumination_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('irrigation_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('planting_date', sa.DateTime(), nullable=True),
    sa.Column('sprouted_seedlings', sa.Integer(), nullable=True),
    sa.Column('current_humidity', sa.Integer(), nullable=True),
    sa.Column('current_temperature', sa.Integer(), nullable=True),
    sa.Column('hours_backlit', sa.Integer(), nullable=True),
    sa.Column('cycle_finished', sa.Boolean(), nullable=True),
    sa.Column('picture_url', sa.String(length=200), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('seedling_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['seedling_id'], ['seedlings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('illuminations_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('illumination_start_date', sa.DateTime(), nullable=False),
    sa.Column('illumination_end_date', sa.DateTime(), nullable=True),
    sa.Column('illumination_mode', sa.Integer(), nullable=False),
    sa.Column('planting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planting_id'], ['plantings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('irrigations_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('irrigation_date', sa.DateTime(), nullable=False),
    sa.Column('irrigation_mode', sa.Integer(), nullable=False),
    sa.Column('planting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planting_id'], ['plantings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('irrigations_history')
    op.drop_table('illuminations_history')
    op.drop_table('plantings')
    op.drop_table('irrigation_schedules')
    op.drop_table('illumination_schedules')
    op.drop_table('seedlings')
    op.drop_table('machines')
    # ### end Alembic commands ###
